### ISSUE TITLE
[osh-metadata.ttl wikibase review] Tracking

### ISSUE THREAD

**Issue by addshore** [OPEN-NEXT/LOSH#35]
I'll use this issue as the main touch point for review of the ontology that exists in this repository.

An initial thought on this topic is that it will likely be easier to initially think about the ontology in terms of Wikibase Items and Properties that need to be created, and thus also their data types, to play around with the modelling.
The TTL descriptions in Wikibase will be based on this, and thus the ttl file in this repo currently will have some differences.

I have done an initial quick pass but feel that we should tackle the potential approach issue first to aid us getting this close to Wikibase terminology and what we will need to do in practice faster.

**Points from first review pass 5-11-2020:**
- [x] #36 okh:name rdfs:subPropertyOf rdfs:label
- [x] #37 "reference" duplications
- [x] #38 okh:name could just be a Wikibase Label (and Aliases?)
- [x] #39 QU: Component language? (okh:language)
- [x] #40 schema:Person, schema:Organization references **<< Highlights the issue more**

**Points from first review pass 4-12-2020:**
- [x] #47 Use of multiple rdfs:comment

**Comment by moedn** [comment]
Thanks for the review! 

I couldn't grasp the issue between the TTL file and Wikibase yet – all the definitions we made in TTL must be made in Wikibase as well, or am I missing something?

Also: How does ontology import in Wikibase work? Can we import the TTL/RDF file directly or do we need to manually rebuild it in the web interface?

**Comment by addshore** [comment]
> I couldn't grasp the issue between the TTL file and Wikibase yet – all the definitions we made in TTL must be made in Wikibase as well, or am I missing something?

Yes, and the resulting TTL that it output from Wikibase my be different from what you have defined in your TTL file.
It will be hard to judge that by eye, the only want to figure out the final RDF output will be to start mapping the data in a Wikibase
